version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "npm"
    ignore:
      - dependency-name: "react"
      - dependency-name: "react-dom"
    groups:
      all-npm-updates:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "actions"
    groups:
      all-action-updates:
        patterns:
          - "*"
